//
// AddAssetsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddAssetsResponseDto: Codable, JSONEncodable, Hashable {

    public var successfullyAdded: Int
    public var alreadyInAlbum: [String]
    public var album: AlbumResponseDto?

    public init(successfullyAdded: Int, alreadyInAlbum: [String], album: AlbumResponseDto? = nil) {
        self.successfullyAdded = successfullyAdded
        self.alreadyInAlbum = alreadyInAlbum
        self.album = album
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case successfullyAdded
        case alreadyInAlbum
        case album
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(successfullyAdded, forKey: .successfullyAdded)
        try container.encode(alreadyInAlbum, forKey: .alreadyInAlbum)
        try container.encodeIfPresent(album, forKey: .album)
    }
}

