//
// AddUsersDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddUsersDto: Codable, JSONEncodable, Hashable {

    public var sharedUserIds: [String]

    public init(sharedUserIds: [String]) {
        self.sharedUserIds = sharedUserIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sharedUserIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sharedUserIds, forKey: .sharedUserIds)
    }
}

