//
// AdminSignupResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminSignupResponseDto: Codable, JSONEncodable, Hashable {

    public var id: String
    public var email: String
    public var firstName: String
    public var lastName: String
    public var createdAt: String

    public init(id: String, email: String, firstName: String, lastName: String, createdAt: String) {
        self.id = id
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case firstName
        case lastName
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

