//
// AllJobStatusResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AllJobStatusResponseDto: Codable, JSONEncodable, Hashable {

    public var thumbnailGenerationQueueCount: JobCounts
    public var metadataExtractionQueueCount: JobCounts
    public var videoConversionQueueCount: JobCounts
    public var machineLearningQueueCount: JobCounts
    public var storageMigrationQueueCount: JobCounts
    public var isThumbnailGenerationActive: Bool
    public var isMetadataExtractionActive: Bool
    public var isVideoConversionActive: Bool
    public var isMachineLearningActive: Bool
    public var isStorageMigrationActive: Bool

    public init(thumbnailGenerationQueueCount: JobCounts, metadataExtractionQueueCount: JobCounts, videoConversionQueueCount: JobCounts, machineLearningQueueCount: JobCounts, storageMigrationQueueCount: JobCounts, isThumbnailGenerationActive: Bool, isMetadataExtractionActive: Bool, isVideoConversionActive: Bool, isMachineLearningActive: Bool, isStorageMigrationActive: Bool) {
        self.thumbnailGenerationQueueCount = thumbnailGenerationQueueCount
        self.metadataExtractionQueueCount = metadataExtractionQueueCount
        self.videoConversionQueueCount = videoConversionQueueCount
        self.machineLearningQueueCount = machineLearningQueueCount
        self.storageMigrationQueueCount = storageMigrationQueueCount
        self.isThumbnailGenerationActive = isThumbnailGenerationActive
        self.isMetadataExtractionActive = isMetadataExtractionActive
        self.isVideoConversionActive = isVideoConversionActive
        self.isMachineLearningActive = isMachineLearningActive
        self.isStorageMigrationActive = isStorageMigrationActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case thumbnailGenerationQueueCount
        case metadataExtractionQueueCount
        case videoConversionQueueCount
        case machineLearningQueueCount
        case storageMigrationQueueCount
        case isThumbnailGenerationActive
        case isMetadataExtractionActive
        case isVideoConversionActive
        case isMachineLearningActive
        case isStorageMigrationActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(thumbnailGenerationQueueCount, forKey: .thumbnailGenerationQueueCount)
        try container.encode(metadataExtractionQueueCount, forKey: .metadataExtractionQueueCount)
        try container.encode(videoConversionQueueCount, forKey: .videoConversionQueueCount)
        try container.encode(machineLearningQueueCount, forKey: .machineLearningQueueCount)
        try container.encode(storageMigrationQueueCount, forKey: .storageMigrationQueueCount)
        try container.encode(isThumbnailGenerationActive, forKey: .isThumbnailGenerationActive)
        try container.encode(isMetadataExtractionActive, forKey: .isMetadataExtractionActive)
        try container.encode(isVideoConversionActive, forKey: .isVideoConversionActive)
        try container.encode(isMachineLearningActive, forKey: .isMachineLearningActive)
        try container.encode(isStorageMigrationActive, forKey: .isStorageMigrationActive)
    }
}

