//
// AssetCountByTimeBucketResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetCountByTimeBucketResponseDto: Codable, JSONEncodable, Hashable {

    public var totalCount: Int
    public var buckets: [AssetCountByTimeBucket]

    public init(totalCount: Int, buckets: [AssetCountByTimeBucket]) {
        self.totalCount = totalCount
        self.buckets = buckets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount
        case buckets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(buckets, forKey: .buckets)
    }
}

