//
// AssetCountByUserIdResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetCountByUserIdResponseDto: Codable, JSONEncodable, Hashable {

    public var audio: Int = 0
    public var photos: Int = 0
    public var videos: Int = 0
    public var other: Int = 0
    public var total: Int = 0

    public init(audio: Int = 0, photos: Int = 0, videos: Int = 0, other: Int = 0, total: Int = 0) {
        self.audio = audio
        self.photos = photos
        self.videos = videos
        self.other = other
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audio
        case photos
        case videos
        case other
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audio, forKey: .audio)
        try container.encode(photos, forKey: .photos)
        try container.encode(videos, forKey: .videos)
        try container.encode(other, forKey: .other)
        try container.encode(total, forKey: .total)
    }
}

