//
// AssetCountByTimeBucket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetCountByTimeBucket: Codable, JSONEncodable, Hashable {

    public var timeBucket: String
    public var count: Int

    public init(timeBucket: String, count: Int) {
        self.timeBucket = timeBucket
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeBucket
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeBucket, forKey: .timeBucket)
        try container.encode(count, forKey: .count)
    }
}

