//
// CheckDuplicateAssetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckDuplicateAssetDto: Codable, JSONEncodable, Hashable {

    public var deviceAssetId: String
    public var deviceId: String

    public init(deviceAssetId: String, deviceId: String) {
        self.deviceAssetId = deviceAssetId
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceAssetId
        case deviceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceAssetId, forKey: .deviceAssetId)
        try container.encode(deviceId, forKey: .deviceId)
    }
}

