//
// CheckDuplicateAssetResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckDuplicateAssetResponseDto: Codable, JSONEncodable, Hashable {

    public var isExist: Bool
    public var id: String?

    public init(isExist: Bool, id: String? = nil) {
        self.isExist = isExist
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isExist
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isExist, forKey: .isExist)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

