//
// CheckExistingAssetsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckExistingAssetsResponseDto: Codable, JSONEncodable, Hashable {

    public var existingIds: [String]

    public init(existingIds: [String]) {
        self.existingIds = existingIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case existingIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(existingIds, forKey: .existingIds)
    }
}

