//
// CreateProfileImageResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateProfileImageResponseDto: Codable, JSONEncodable, Hashable {

    public var userId: String
    public var profileImagePath: String

    public init(userId: String, profileImagePath: String) {
        self.userId = userId
        self.profileImagePath = profileImagePath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case profileImagePath
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(profileImagePath, forKey: .profileImagePath)
    }
}

