//
// CreateTagDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateTagDto: Codable, JSONEncodable, Hashable {

    public var type: TagTypeEnum
    public var name: String

    public init(type: TagTypeEnum, name: String) {
        self.type = type
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
    }
}

