//
// CuratedObjectsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CuratedObjectsResponseDto: Codable, JSONEncodable, Hashable {

    public var id: String
    public var object: String
    public var resizePath: String
    public var deviceAssetId: String
    public var deviceId: String

    public init(id: String, object: String, resizePath: String, deviceAssetId: String, deviceId: String) {
        self.id = id
        self.object = object
        self.resizePath = resizePath
        self.deviceAssetId = deviceAssetId
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case object
        case resizePath
        case deviceAssetId
        case deviceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(object, forKey: .object)
        try container.encode(resizePath, forKey: .resizePath)
        try container.encode(deviceAssetId, forKey: .deviceAssetId)
        try container.encode(deviceId, forKey: .deviceId)
    }
}

