//
// DeleteAssetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteAssetDto: Codable, JSONEncodable, Hashable {

    public var ids: [String]

    public init(ids: [String]) {
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ids, forKey: .ids)
    }
}

