//
// DeleteAssetStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DeleteAssetStatus: String, Codable, CaseIterable {
    case success = "SUCCESS"
    case failed = "FAILED"
}
