//
// DeviceTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DeviceTypeEnum: String, Codable, CaseIterable {
    case ios = "IOS"
    case android = "ANDROID"
    case web = "WEB"
}
