//
// DeviceInfoResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeviceInfoResponseDto: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var deviceType: DeviceTypeEnum
    public var userId: String
    public var deviceId: String
    public var createdAt: String
    public var isAutoBackup: Bool

    public init(id: Int, deviceType: DeviceTypeEnum, userId: String, deviceId: String, createdAt: String, isAutoBackup: Bool) {
        self.id = id
        self.deviceType = deviceType
        self.userId = userId
        self.deviceId = deviceId
        self.createdAt = createdAt
        self.isAutoBackup = isAutoBackup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case deviceType
        case userId
        case deviceId
        case createdAt
        case isAutoBackup
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(deviceType, forKey: .deviceType)
        try container.encode(userId, forKey: .userId)
        try container.encode(deviceId, forKey: .deviceId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(isAutoBackup, forKey: .isAutoBackup)
    }
}

