//
// JobCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JobCounts: Codable, JSONEncodable, Hashable {

    public var active: Int
    public var completed: Int
    public var failed: Int
    public var delayed: Int
    public var waiting: Int

    public init(active: Int, completed: Int, failed: Int, delayed: Int, waiting: Int) {
        self.active = active
        self.completed = completed
        self.failed = failed
        self.delayed = delayed
        self.waiting = waiting
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case active
        case completed
        case failed
        case delayed
        case waiting
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(active, forKey: .active)
        try container.encode(completed, forKey: .completed)
        try container.encode(failed, forKey: .failed)
        try container.encode(delayed, forKey: .delayed)
        try container.encode(waiting, forKey: .waiting)
    }
}

