//
// JobCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum JobCommand: String, Codable, CaseIterable {
    case start = "start"
    case stop = "stop"
}
