//
// JobId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum JobId: String, Codable, CaseIterable {
    case thumbnailGeneration = "thumbnail-generation"
    case metadataExtraction = "metadata-extraction"
    case videoConversion = "video-conversion"
    case machineLearning = "machine-learning"
    case storageTemplateMigration = "storage-template-migration"
}
