//
// LogoutResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LogoutResponseDto: Codable, JSONEncodable, Hashable {

    public var successful: Bool
    public var redirectUri: String

    public init(successful: Bool, redirectUri: String) {
        self.successful = successful
        self.redirectUri = redirectUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case successful
        case redirectUri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(successful, forKey: .successful)
        try container.encode(redirectUri, forKey: .redirectUri)
    }
}

