//
// OAuthConfigResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OAuthConfigResponseDto: Codable, JSONEncodable, Hashable {

    public var enabled: Bool
    public var url: String?
    public var buttonText: String?

    public init(enabled: Bool, url: String? = nil, buttonText: String? = nil) {
        self.enabled = enabled
        self.url = url
        self.buttonText = buttonText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case url
        case buttonText
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(buttonText, forKey: .buttonText)
    }
}

