//
// OAuthConfigDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OAuthConfigDto: Codable, JSONEncodable, Hashable {

    public var redirectUri: String

    public init(redirectUri: String) {
        self.redirectUri = redirectUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirectUri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirectUri, forKey: .redirectUri)
    }
}

