//
// RemoveAssetsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RemoveAssetsDto: Codable, JSONEncodable, Hashable {

    public var assetIds: [String]

    public init(assetIds: [String]) {
        self.assetIds = assetIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetIds, forKey: .assetIds)
    }
}

