//
// SearchAssetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchAssetDto: Codable, JSONEncodable, Hashable {

    public var searchTerm: String

    public init(searchTerm: String) {
        self.searchTerm = searchTerm
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchTerm
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(searchTerm, forKey: .searchTerm)
    }
}

