//
// ServerVersionReponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerVersionReponseDto: Codable, JSONEncodable, Hashable {

    public var major: Int
    public var minor: Int
    public var patch: Int
    public var build: Int

    public init(major: Int, minor: Int, patch: Int, build: Int) {
        self.major = major
        self.minor = minor
        self.patch = patch
        self.build = build
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case major
        case minor
        case patch
        case build
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(major, forKey: .major)
        try container.encode(minor, forKey: .minor)
        try container.encode(patch, forKey: .patch)
        try container.encode(build, forKey: .build)
    }
}

