//
// ServerStatsResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerStatsResponseDto: Codable, JSONEncodable, Hashable {

    public var photos: Int
    public var videos: Int
    public var objects: Int
    public var usageRaw: Int64
    public var usage: String
    public var usageByUser: [UsageByUserDto]

    public init(photos: Int, videos: Int, objects: Int, usageRaw: Int64, usage: String, usageByUser: [UsageByUserDto]) {
        self.photos = photos
        self.videos = videos
        self.objects = objects
        self.usageRaw = usageRaw
        self.usage = usage
        self.usageByUser = usageByUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case photos
        case videos
        case objects
        case usageRaw
        case usage
        case usageByUser
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(photos, forKey: .photos)
        try container.encode(videos, forKey: .videos)
        try container.encode(objects, forKey: .objects)
        try container.encode(usageRaw, forKey: .usageRaw)
        try container.encode(usage, forKey: .usage)
        try container.encode(usageByUser, forKey: .usageByUser)
    }
}

