//
// ServerPingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerPingResponse: Codable, JSONEncodable, Hashable {

    public var res: String

    public init(res: String) {
        self.res = res
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case res
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(res, forKey: .res)
    }
}

