//
// ServerInfoResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerInfoResponseDto: Codable, JSONEncodable, Hashable {

    public var diskSizeRaw: Int64
    public var diskUseRaw: Int64
    public var diskAvailableRaw: Int64
    public var diskUsagePercentage: Float
    public var diskSize: String
    public var diskUse: String
    public var diskAvailable: String

    public init(diskSizeRaw: Int64, diskUseRaw: Int64, diskAvailableRaw: Int64, diskUsagePercentage: Float, diskSize: String, diskUse: String, diskAvailable: String) {
        self.diskSizeRaw = diskSizeRaw
        self.diskUseRaw = diskUseRaw
        self.diskAvailableRaw = diskAvailableRaw
        self.diskUsagePercentage = diskUsagePercentage
        self.diskSize = diskSize
        self.diskUse = diskUse
        self.diskAvailable = diskAvailable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case diskSizeRaw
        case diskUseRaw
        case diskAvailableRaw
        case diskUsagePercentage
        case diskSize
        case diskUse
        case diskAvailable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(diskSizeRaw, forKey: .diskSizeRaw)
        try container.encode(diskUseRaw, forKey: .diskUseRaw)
        try container.encode(diskAvailableRaw, forKey: .diskAvailableRaw)
        try container.encode(diskUsagePercentage, forKey: .diskUsagePercentage)
        try container.encode(diskSize, forKey: .diskSize)
        try container.encode(diskUse, forKey: .diskUse)
        try container.encode(diskAvailable, forKey: .diskAvailable)
    }
}

