//
// SmartInfoResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SmartInfoResponseDto: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var tags: [String]?
    public var objects: [String]?

    public init(id: String? = nil, tags: [String]? = nil, objects: [String]? = nil) {
        self.id = id
        self.tags = tags
        self.objects = objects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tags
        case objects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(objects, forKey: .objects)
    }
}

