//
// SystemConfigOAuthDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemConfigOAuthDto: Codable, JSONEncodable, Hashable {

    public var enabled: Bool
    public var issuerUrl: String
    public var clientId: String
    public var clientSecret: String
    public var scope: String
    public var buttonText: String
    public var autoRegister: Bool

    public init(enabled: Bool, issuerUrl: String, clientId: String, clientSecret: String, scope: String, buttonText: String, autoRegister: Bool) {
        self.enabled = enabled
        self.issuerUrl = issuerUrl
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.scope = scope
        self.buttonText = buttonText
        self.autoRegister = autoRegister
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case issuerUrl
        case clientId
        case clientSecret
        case scope
        case buttonText
        case autoRegister
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(issuerUrl, forKey: .issuerUrl)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(clientSecret, forKey: .clientSecret)
        try container.encode(scope, forKey: .scope)
        try container.encode(buttonText, forKey: .buttonText)
        try container.encode(autoRegister, forKey: .autoRegister)
    }
}

