//
// SystemConfigTemplateStorageOptionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemConfigTemplateStorageOptionDto: Codable, JSONEncodable, Hashable {

    public var yearOptions: [String]
    public var monthOptions: [String]
    public var dayOptions: [String]
    public var hourOptions: [String]
    public var minuteOptions: [String]
    public var secondOptions: [String]
    public var presetOptions: [String]

    public init(yearOptions: [String], monthOptions: [String], dayOptions: [String], hourOptions: [String], minuteOptions: [String], secondOptions: [String], presetOptions: [String]) {
        self.yearOptions = yearOptions
        self.monthOptions = monthOptions
        self.dayOptions = dayOptions
        self.hourOptions = hourOptions
        self.minuteOptions = minuteOptions
        self.secondOptions = secondOptions
        self.presetOptions = presetOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case yearOptions
        case monthOptions
        case dayOptions
        case hourOptions
        case minuteOptions
        case secondOptions
        case presetOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(yearOptions, forKey: .yearOptions)
        try container.encode(monthOptions, forKey: .monthOptions)
        try container.encode(dayOptions, forKey: .dayOptions)
        try container.encode(hourOptions, forKey: .hourOptions)
        try container.encode(minuteOptions, forKey: .minuteOptions)
        try container.encode(secondOptions, forKey: .secondOptions)
        try container.encode(presetOptions, forKey: .presetOptions)
    }
}

