//
// SystemConfigStorageTemplateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemConfigStorageTemplateDto: Codable, JSONEncodable, Hashable {

    public var template: String

    public init(template: String) {
        self.template = template
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case template
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(template, forKey: .template)
    }
}

