//
// TagResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TagResponseDto: Codable, JSONEncodable, Hashable {

    public var id: String
    public var type: TagTypeEnum
    public var name: String
    public var userId: String
    public var renameTagId: String?

    public init(id: String, type: TagTypeEnum, name: String, userId: String, renameTagId: String? = nil) {
        self.id = id
        self.type = type
        self.name = name
        self.userId = userId
        self.renameTagId = renameTagId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case name
        case userId
        case renameTagId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(renameTagId, forKey: .renameTagId)
    }
}

