//
// TagTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TagTypeEnum: String, Codable, CaseIterable {
    case object = "OBJECT"
    case face = "FACE"
    case custom = "CUSTOM"
}
