//
// TimeGroupEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TimeGroupEnum: String, Codable, CaseIterable {
    case day = "day"
    case month = "month"
}
