//
// UpdateAssetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateAssetDto: Codable, JSONEncodable, Hashable {

    public var tagIds: [String]?
    public var isFavorite: Bool?

    public init(tagIds: [String]? = nil, isFavorite: Bool? = nil) {
        self.tagIds = tagIds
        self.isFavorite = isFavorite
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tagIds
        case isFavorite
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tagIds, forKey: .tagIds)
        try container.encodeIfPresent(isFavorite, forKey: .isFavorite)
    }
}

