//
// UpdateTagDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateTagDto: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var renameTagId: String?

    public init(name: String? = nil, renameTagId: String? = nil) {
        self.name = name
        self.renameTagId = renameTagId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case renameTagId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(renameTagId, forKey: .renameTagId)
    }
}

