//
// UpsertDeviceInfoDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpsertDeviceInfoDto: Codable, JSONEncodable, Hashable {

    public var deviceType: DeviceTypeEnum
    public var deviceId: String
    public var isAutoBackup: Bool?

    public init(deviceType: DeviceTypeEnum, deviceId: String, isAutoBackup: Bool? = nil) {
        self.deviceType = deviceType
        self.deviceId = deviceId
        self.isAutoBackup = isAutoBackup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceType
        case deviceId
        case isAutoBackup
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceType, forKey: .deviceType)
        try container.encode(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(isAutoBackup, forKey: .isAutoBackup)
    }
}

