//
// UsageByUserDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsageByUserDto: Codable, JSONEncodable, Hashable {

    public var userId: String
    public var videos: Int
    public var photos: Int
    public var usageRaw: Int64
    public var usage: String

    public init(userId: String, videos: Int, photos: Int, usageRaw: Int64, usage: String) {
        self.userId = userId
        self.videos = videos
        self.photos = photos
        self.usageRaw = usageRaw
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case videos
        case photos
        case usageRaw
        case usage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(videos, forKey: .videos)
        try container.encode(photos, forKey: .photos)
        try container.encode(usageRaw, forKey: .usageRaw)
        try container.encode(usage, forKey: .usage)
    }
}

